version: '3.8'

services:
  dbpg:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=training_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'  # Mapping container port 5432 to host port 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend_network
  
  web:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=dbpg  # Use the service name defined in docker-compose.yml
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=training_db
    ports:
      - '8000:8000'
    depends_on:
      - dbpg
    networks:
      - backend_network

volumes:
  pg_data:

networks:
  backend_network:
